### ISSUE TITLE
Fails to decode JSON on start.

### ISSUE THREAD

**Issue by PierreLeGuen** [rbignon/doctoshotgun#309]
Since this morning the script isn’t able to start. Please, find below the error I get:

```
~/doctoshotgun$ ./doctoshotgun.py fr brest mail@gmail.com
Password: 

Traceback (most recent call last):
  File "/home/user/doctoshotgun/./doctoshotgun.py", line 949, in <module>
    sys.exit(Application().main())
  File "/home/user/doctoshotgun/./doctoshotgun.py", line 744, in main
    docto.load_state(self.load_state())
  File "/home/user/doctoshotgun/./doctoshotgun.py", line 662, in load_state
    state = json.load(fp)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by nicolaus-hee** [comment]
I cannot replicate.

**Comment by PierreLeGuen** [comment]
Did you try with 2FA account?

**Comment by nicolaus-hee** [comment]
Yes
