### ISSUE TITLE
Error 404 for getting list of centers

### ISSUE THREAD

**Issue by sgoendoer** [rbignon/doctoshotgun#50]
Hi,

first of all, great work! Thanks a lot!!!

Anyhow, I get an error for running my script on Mac 11.4, Python 3.9.5, pip 21.1.2 for the city of Berlin:

```
./doctoshotgun.py berlin username@email.com
Password:
Starting to look for vaccine slots for real_name in 7 next day(s)...
Vaccines: Pfizer, Moderna
This may take a few minutes/hours, be patient!
Traceback (most recent call last):
  File "/Users/user/Documents/git/doctoshotgun/./doctoshotgun.py", line 489, in <module>
    sys.exit(Application().main())
  File "/Users/user/Documents/git/doctoshotgun/./doctoshotgun.py", line 462, in main
    for center in docto.find_centers(cities, motives):
  File "/Users/user/Documents/git/doctoshotgun/./doctoshotgun.py", line 203, in find_centers
    self.centers.go(where=city, params={'ref_visit_motive_ids[]': motives})
  File "/usr/local/lib/python3.9/site-packages/woob/browser/url.py", line 98, in go
    r = self.browser.location(self.build(**kwargs), params=params, data=data, json=json, method=method, headers=headers or {})
  File "/usr/local/lib/python3.9/site-packages/woob/browser/browsers.py", line 911, in location
    response = self.open(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/woob/browser/browsers.py", line 898, in open
    return super(PagesBrowser, self).open(callback=internal_callback, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/woob/browser/browsers.py", line 790, in open
    return super(DomainBrowser, self).open(req, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/woob/browser/browsers.py", line 531, in open
    response = self.session.send(preq,
  File "/Users/user/Documents/git/doctoshotgun/./doctoshotgun.py", line 57, in send
    return callback(self, resp)
  File "/usr/local/lib/python3.9/site-packages/woob/browser/browsers.py", line 527, in inner_callback
    self.raise_for_status(response)
  File "/usr/local/lib/python3.9/site-packages/woob/browser/browsers.py", line 559, in raise_for_status
    raise HTTPNotFound(http_error_msg, response=response)
woob.browser.exceptions.HTTPNotFound: 404 Client Error: Not Found
```

Seems to me that the "find_centers" returns something unexpected. The displayed name at the beginning is correct, hence the login seems to be working.

Interestingly, the same script/login works for the city of Paris for me:

```
./doctoshotgun.py paris username@email.com
Password:
Starting to look for vaccine slots for real_name in 7 next day(s)...
Vaccines: Pfizer, Moderna
This may take a few minutes/hours, be patient!

Center SOS Médecins Grand Paris:
– SOS Médecins - Consultations Paris 13... no availabilities
– SOS Médecins - Consultations Paris 19... no availabilities
– SOS Médecins - Consultations Paris 17e... no availabilities
– Centre vaccinations COVID SOS Médecins Paris-17 ... found!
  ├╴ Best slot found: Fri Jun  5 13:45:00 2021
  ├╴ Second shot: Fri Jul 17 13:45:00 2021
  ├╴ Booking for real_name...
  └╴ Booking status: True

💉 Booked! Congratulations.
```

**Comment by rbignon** [comment]
Hello,

Thank you for your report. Currently doctoshotgun works only in France. You can try this fork which has been modified to work with doctolib.de: https://github.com/LinqLover/doctoshotgun

Perhaps in the future I'll try to include these changes to let doctoshotgun works in several countries.

**Comment by sgoendoer** [comment]
Thanks a lot. The fork you mentioned seemed broken and didn't work for me. I managed to include it's changes into a new fork of this repository. This works for me now :)
